# Generated by Django 6.0.5 on 2026-05-22 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('role', models.CharField(choices=[('super_admin', 'Super administrateur'), ('editeur', 'Éditeur'), ('lecteur', 'Lecteur')], default='editeur', max_length=20, verbose_name='Rôle')),
                ('photo', models.ImageField(blank=True, help_text='Photo carrée recommandée', null=True, upload_to='profils/', verbose_name='Photo de profil')),
                ('biographie', models.TextField(blank=True, help_text='Courte présentation, affichée sur les articles', verbose_name='Biographie')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('fonction', models.CharField(blank=True, help_text='Ex: Directeur, Responsable communication, Secrétaire', max_length=100, verbose_name='Fonction')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
    ]
