# Generated by Django 6.0.5 on 2026-05-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('nom', models.CharField(help_text='Nom et prénom de la personne', max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('telephone', models.CharField(blank=True, help_text='Numéro de téléphone (optionnel)', max_length=30, verbose_name='Téléphone')),
                ('sujet', models.CharField(choices=[('info', "Demande d'information"), ('admission', "Question sur l'admission"), ('formation', 'Question sur les formations'), ('partenariat', 'Proposition de partenariat'), ('autre', 'Autre')], default='info', max_length=20, verbose_name='Sujet')),
                ('message', models.TextField(help_text='Contenu du message', verbose_name='Message')),
                ('statut', models.CharField(choices=[('non_lu', 'Non lu'), ('lu', 'Lu'), ('traite', 'Traité')], default='non_lu', max_length=10, verbose_name='Statut')),
                ('note_interne', models.TextField(blank=True, help_text="Notes privées de l'équipe (non visible par l'expéditeur)", verbose_name='Note interne')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
