# Generated by Django 6.0.5 on 2026-05-21 11:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('nom', models.CharField(help_text='Ex: Événement, Communiqué, Vie scolaire', max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(help_text='Auto-généré depuis le nom si laissé vide', max_length=100, unique=True, verbose_name='Slug URL')),
                ('description', models.CharField(blank=True, help_text='Affichée sur la page de catégorie', max_length=200, verbose_name='Description courte')),
                ('couleur', models.CharField(choices=[('primary', 'Vert (par défaut)'), ('accent', 'Or'), ('blue', 'Bleu'), ('red', 'Rouge'), ('purple', 'Violet')], default='primary', help_text="Couleur d'affichage des badges de cette catégorie", max_length=20, verbose_name='Couleur')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug URL')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(help_text='Auto-généré depuis le titre. Modifier avec prudence (URLs publiques)', max_length=200, unique_for_date='date_publication', verbose_name='Slug URL')),
                ('resume', models.CharField(help_text="Phrase d'accroche affichée sur la liste et les partages sociaux", max_length=300, verbose_name='Résumé')),
                ('contenu', models.TextField(help_text="Texte complet de l'article. HTML autorisé.", verbose_name='Contenu')),
                ('image_une', models.ImageField(help_text="Image principale de l'article. Format paysage recommandé.", upload_to='blog/articles/%Y/%m/', verbose_name='Image à la une')),
                ('image_une_alt', models.CharField(help_text="Description courte de l'image (accessibilité, SEO)", max_length=200, verbose_name='Texte alternatif image')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', help_text='Brouillon = invisible sur le site. Publié = visible.', max_length=20, verbose_name='Statut')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, help_text="Date à partir de laquelle l'article est visible. Permet de programmer une publication future.", verbose_name='Date de publication')),
                ('est_a_la_une', models.BooleanField(default=False, help_text='Mettre en avant cet article (homepage)', verbose_name='À la une')),
                ('nombre_vues', models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de vues')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='blog.categorie', verbose_name='Catégorie')),
                ('tags', models.ManyToManyField(blank=True, help_text='Mots-clés pour affiner la recherche', related_name='articles', to='blog.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication'],
                'indexes': [models.Index(fields=['-date_publication'], name='blog_articl_date_pu_587a62_idx'), models.Index(fields=['statut', '-date_publication'], name='blog_articl_statut_d30545_idx')],
            },
        ),
    ]
