# Generated by Django 6.0.5 on 2026-05-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembreDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('fonction', models.CharField(help_text='Ex: Directeur, Directeur des Études, Censeur', max_length=150, verbose_name='Fonction')),
                ('biographie', models.TextField(blank=True, help_text='Courte biographie / parcours professionnel', verbose_name='Biographie')),
                ('citation', models.TextField(blank=True, help_text='Citation à afficher (notamment pour le directeur)', verbose_name='Citation / Mot')),
                ('photo', models.ImageField(blank=True, help_text='Photo professionnelle - format carré recommandé', null=True, upload_to='equipe/', verbose_name='Photo')),
                ('est_directeur', models.BooleanField(default=False, help_text='Cochez pour le directeur principal (affichage spécial)', verbose_name='Est le directeur')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Membre de la direction',
                'verbose_name_plural': 'Membres de la direction',
                'ordering': ['ordre', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('nom_etablissement', models.CharField(default="ENIET / ENIEG de l'Excellence Professionnelle", help_text='Affiché dans le footer et les emails', max_length=200, verbose_name="Nom de l'établissement")),
                ('devise', models.CharField(blank=True, default='Excellence Professionnelle', max_length=200, verbose_name='Devise')),
                ('description_courte', models.TextField(default="École Normale d'Instituteurs de l'Enseignement Général et Technique. Établissement agréé par le MINESEC.", help_text='Utilisée dans le footer et les méta-descriptions par défaut', max_length=500, verbose_name='Description courte')),
                ('email_principal', models.EmailField(default='efpsaf@yahoo.fr', max_length=254, verbose_name='Email principal')),
                ('email_contact', models.EmailField(default='efpsaf@yahoo.fr', help_text='Email qui reçoit les messages du formulaire de contact', max_length=254, verbose_name='Email de contact')),
                ('telephone_1', models.CharField(default='+237 696 16 20 16', max_length=30, verbose_name='Téléphone principal')),
                ('telephone_2', models.CharField(blank=True, default='+237 672 46 70 70', max_length=30, verbose_name='Téléphone secondaire')),
                ('telephone_3', models.CharField(blank=True, default='+237 678 46 96 64', max_length=30, verbose_name='Téléphone 3')),
                ('adresse_ligne_1', models.CharField(default='Yassa, Entrée Planète Voyage', max_length=200, verbose_name='Adresse - ligne 1')),
                ('adresse_ligne_2', models.CharField(blank=True, default='Douala, Cameroun', max_length=200, verbose_name='Adresse - ligne 2')),
                ('boite_postale', models.CharField(blank=True, default='BP 4100 Douala', max_length=50, verbose_name='Boîte postale')),
                ('latitude', models.DecimalField(decimal_places=7, default=4.0511, help_text='Coordonnée GPS pour la carte (ex: 4.0511 pour Douala)', max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, default=9.7547, help_text='Coordonnée GPS pour la carte', max_digits=10, verbose_name='Longitude')),
                ('horaires_semaine', models.CharField(blank=True, default='07h30 — 17h00', max_length=100, verbose_name='Horaires lundi-vendredi')),
                ('horaires_samedi', models.CharField(blank=True, default='08h00 — 13h00', max_length=100, verbose_name='Horaires samedi')),
                ('facebook_url', models.URLField(blank=True, verbose_name='URL Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='URL Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='URL YouTube')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='URL LinkedIn')),
                ('arrete_eniet', models.CharField(blank=True, default='n°69/15/MINESEC/SEESEN/SG/DPN/SDENT/SGENPRI du 21 Avril 2015', max_length=100, verbose_name='N° arrêté ENIET')),
                ('arrete_enieg', models.CharField(blank=True, default='n°26/15/MINESEC/SEESEN/SG/DEN/SDENG/SSGENPRI du 27 Janvier 2015', max_length=100, verbose_name='N° arrêté ENIEG')),
                ('annee_scolaire', models.CharField(default='2025-2026', help_text='Format : YYYY-YYYY', max_length=20, verbose_name='Année scolaire en cours')),
            ],
            options={
                'verbose_name': 'Paramètre du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('titre', models.CharField(help_text='Ex: Excellence, Rigueur, Intégrité', max_length=100, verbose_name='Titre de la valeur')),
                ('description', models.TextField(help_text='Courte description de la valeur', verbose_name='Description')),
                ('icone', models.CharField(default='star', help_text="Identifiant d'icône : star, shield, heart, book, etc.", max_length=10, verbose_name='Icône SVG path')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='Plus le nombre est petit, plus la valeur apparaît en premier', verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, help_text='Décocher pour masquer cette valeur sans la supprimer', verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Valeur de l'établissement",
                'verbose_name_plural': "Valeurs de l'établissement",
                'ordering': ['ordre', 'created_at'],
            },
        ),
    ]
