# Generated by Django 6.0.5 on 2026-05-21 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_donnees_initiales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'album")),
                ('slug', models.SlugField(help_text="Identifiant pour l'URL (généré automatiquement)", max_length=200, unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(blank=True, help_text="Présentation de l'événement, contexte", verbose_name='Description')),
                ('date_evenement', models.DateField(help_text="Date à laquelle l'événement a eu lieu", verbose_name="Date de l'événement")),
                ('couverture', models.ImageField(blank=True, help_text="Optionnel - si vide, on utilise la 1ère photo de l'album", null=True, upload_to='galerie/couvertures/', verbose_name='Photo de couverture')),
                ('est_a_la_une', models.BooleanField(default=False, help_text='Mettre en avant cet album', verbose_name='À la une')),
                ('publie', models.BooleanField(default=True, help_text="Décocher pour cacher l'album sans le supprimer", verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Album photo',
                'verbose_name_plural': 'Albums photos',
                'ordering': ['-date_evenement', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('image', models.ImageField(help_text='Format JPG ou PNG, taille recommandée : 1920x1080 max', upload_to='galerie/photos/%Y/%m/', verbose_name='Image')),
                ('legende', models.CharField(blank=True, help_text='Description de la photo (visible au survol et dans le lightbox)', max_length=300, verbose_name='Légende')),
                ('alt', models.CharField(help_text="Description courte pour les lecteurs d'écran (accessibilité)", max_length=200, verbose_name='Texte alternatif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='Plus le nombre est petit, plus la photo apparaît en premier', verbose_name="Ordre d'affichage")),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pages.album', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['ordre', 'created_at'],
            },
        ),
    ]
