# Generated by Django 6.0.5 on 2026-05-21 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('libelle', models.CharField(help_text='Ex: "Photocopie CNI"', max_length=200, verbose_name='Document')),
                ('description', models.CharField(blank=True, help_text='Détails optionnels (format, exigences...)', max_length=300, verbose_name='Précision')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Document requis',
                'verbose_name_plural': 'Documents requis',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('nom', models.CharField(help_text="Ex: École Normale d'Instituteurs de l'Enseignement Général", max_length=200, verbose_name='Nom complet')),
                ('sigle', models.CharField(help_text='Ex: ENIEG ou ENIET', max_length=10, unique=True, verbose_name='Sigle')),
                ('slug', models.SlugField(help_text="Identifiant pour l'URL, en minuscules sans accents", max_length=20, unique=True, verbose_name='Slug URL')),
                ('type_ecole', models.CharField(choices=[('general', 'Enseignement Général'), ('technique', 'Enseignement Technique')], max_length=20, verbose_name='Type')),
                ('diplome_prepare', models.CharField(help_text='Ex: CAPIEMP ou CAPIET', max_length=100, verbose_name='Diplôme préparé')),
                ('diplome_complet', models.CharField(help_text="Ex: Certificat d'Aptitude Pédagogique d'Instituteurs...", max_length=300, verbose_name='Intitulé complet du diplôme')),
                ('description_courte', models.TextField(help_text="Affichée sur la page d'accueil et la liste des écoles", max_length=500, verbose_name='Description courte')),
                ('description_longue', models.TextField(blank=True, help_text="Affichée sur la page admission de l'école", verbose_name='Description détaillée')),
                ('pre_requis', models.TextField(help_text='Diplômes acceptés : Bac, BT, BP, etc.', verbose_name="Pré-requis d'admission")),
                ('duree_formation', models.CharField(default='2 ans', max_length=50, verbose_name='Durée de la formation')),
                ('frais_concours', models.PositiveIntegerField(default=12000, help_text="Frais d'inscription au concours, non remboursables", verbose_name='Frais de concours (FCFA)')),
                ('frais_inscription_non_remboursable', models.PositiveIntegerField(default=25000, verbose_name='Inscription non remboursable (FCFA)')),
                ('matiere_oeuvre', models.PositiveIntegerField(default=0, help_text="Frais de matière d'œuvre - 0 pour ENIEG, 25000 pour ENIET", verbose_name="Matière d'œuvre (FCFA)")),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'École',
                'verbose_name_plural': 'Écoles',
                'ordering': ['ordre', 'sigle'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('reponse', models.TextField(verbose_name='Réponse')),
                ('categorie', models.CharField(choices=[('admission', 'Admission'), ('formation', 'Formation'), ('frais', 'Frais et paiement'), ('autre', 'Autre')], default='admission', max_length=20, verbose_name='Catégorie')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Question fréquente',
                'verbose_name_plural': 'Questions fréquentes',
                'ordering': ['categorie', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='TranchePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('annee', models.PositiveSmallIntegerField(choices=[(1, '1ère année'), (2, '2ème année')], help_text='À quelle année concerne cette tranche', verbose_name='Année de scolarité')),
                ('numero_tranche', models.PositiveSmallIntegerField(help_text='1 pour la 1ère tranche, 2 pour la 2ème, etc.', verbose_name='Numéro de tranche')),
                ('libelle', models.CharField(help_text='Ex: "1ère tranche", "2ème tranche"', max_length=100, verbose_name='Libellé')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant (FCFA)')),
                ('echeance', models.CharField(help_text='Ex: "À l\'inscription", "Le 10 décembre"', max_length=100, verbose_name='Échéance')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='ecoles.ecole', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Tranche de paiement',
                'verbose_name_plural': 'Tranches de paiement',
                'ordering': ['ecole', 'annee', 'numero_tranche'],
                'unique_together': {('ecole', 'annee', 'numero_tranche')},
            },
        ),
    ]
