# Generated by Django 6.0.5 on 2026-05-21 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0002_donnees_initiales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('nom', models.CharField(help_text='Ex: Électricité, Couture, Bureautique', max_length=150, verbose_name='Nom de la filière')),
                ('slug', models.SlugField(help_text="Identifiant pour l'URL (sans accent, en minuscules)", verbose_name='Slug URL')),
                ('description_courte', models.CharField(help_text="Phrase d'accroche affichée sur les cartes", max_length=250, verbose_name='Description courte')),
                ('description_longue', models.TextField(blank=True, help_text='Présentation complète, affichée sur la page de détail', verbose_name='Description détaillée')),
                ('debouches', models.TextField(blank=True, help_text='Métiers et opportunités après la formation', verbose_name='Débouchés professionnels')),
                ('competences_acquises', models.TextField(blank=True, help_text='Une compétence par ligne', verbose_name='Compétences acquises')),
                ('matieres_principales', models.TextField(blank=True, help_text='Une matière par ligne', verbose_name='Matières principales')),
                ('icone', models.CharField(default='briefcase', help_text="Identifiant d'icône : bolt, building, scissors, chart, computer...", max_length=20, verbose_name='Icône')),
                ('image', models.ImageField(blank=True, help_text="Photo d'illustration de la filière", null=True, upload_to='filieres/', verbose_name='Image illustrative')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='ecoles.ecole', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['ecole', 'ordre', 'nom'],
                'unique_together': {('ecole', 'slug')},
            },
        ),
    ]
